### ISSUE TITLE
browsing to the Volto frontend does not render page correctly

### ISSUE THREAD

**Issue by tkimnguyen** [plone/2024.ploneconf.org#11]
Lots of things are missing when browsing to http://localhost:3000

![Screenshot 2024-09-11 at 9 13 41 AM](https://github.com/user-attachments/assets/e1e4818e-7b66-4937-87d6-e83e3682735f)

And below is what appears in the terminal:

```
🎭 Volto started at 0.0.0.0:3000 🚀
Warning: Failed prop type: The prop `index` is marked as required in `Memo`, but its value is `undefined`.
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:105118:5
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:74014:5
    at StyleWrapper (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:34385:5)
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at div
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at RenderBlocks (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:95664:5)
    at div
    at $2e5fe81f2b094176$export$42a852a2b6b56249 (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:125707:17)
    at DefaultView (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:66301:5)
    at div
    at View (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:67570:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(View))
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at main
    at div
    at Segment (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/semantic-ui-react@2.1.5_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/semantic-ui-react/dist/commonjs/elements/Segment/Segment.js:28:24)
    at MultilingualRedirector (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:62687:5)
    at PluggablesProvider (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:50358:3)
    at App (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:59196:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(App))
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at AsyncConnect (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72173:5)
    at AsyncConnectWithContext (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72291:7)
    at C (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:731:37)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Router (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:99:30)
    at StaticRouter (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:587:35)
    at IntlProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl@3.12.1_react@18.2.0/node_modules/react-intl/dist/components/provider.js:89:47)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/Provider.js:19:3)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl-redux@2.3.0_@babel+runtime@7.20.6_prop-types@15.7.2_react-intl@3.12.1_react@18.2.0_tgk6nn4hyyhqsgqquyp6ne3siq/node_modules/react-intl-redux/lib/components/Provider.js:19:20)
    at CookiesProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-cookie@4.1.1_react@18.2.0/node_modules/react-cookie/cjs/CookiesProvider.js:52:24)
    at ChunkExtractorManager (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/@loadable+server@5.14.0_@loadable+component@5.14.1_react@18.2.0__react@18.2.0/node_modules/@loadable/server/lib/ChunkExtractorManager.js:13:3)
Warning: Failed prop type: The prop `selected` is marked as required in `Memo`, but its value is `undefined`.
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:105118:5
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:74014:5
    at StyleWrapper (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:34385:5)
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at div
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at RenderBlocks (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:95664:5)
    at div
    at $2e5fe81f2b094176$export$42a852a2b6b56249 (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:125707:17)
    at DefaultView (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:66301:5)
    at div
    at View (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:67570:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(View))
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at main
    at div
    at Segment (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/semantic-ui-react@2.1.5_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/semantic-ui-react/dist/commonjs/elements/Segment/Segment.js:28:24)
    at MultilingualRedirector (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:62687:5)
    at PluggablesProvider (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:50358:3)
    at App (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:59196:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(App))
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at AsyncConnect (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72173:5)
    at AsyncConnectWithContext (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72291:7)
    at C (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:731:37)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Router (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:99:30)
    at StaticRouter (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:587:35)
    at IntlProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl@3.12.1_react@18.2.0/node_modules/react-intl/dist/components/provider.js:89:47)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/Provider.js:19:3)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl-redux@2.3.0_@babel+runtime@7.20.6_prop-types@15.7.2_react-intl@3.12.1_react@18.2.0_tgk6nn4hyyhqsgqquyp6ne3siq/node_modules/react-intl-redux/lib/components/Provider.js:19:20)
    at CookiesProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-cookie@4.1.1_react@18.2.0/node_modules/react-cookie/cjs/CookiesProvider.js:52:24)
    at ChunkExtractorManager (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/@loadable+server@5.14.0_@loadable+component@5.14.1_react@18.2.0__react@18.2.0/node_modules/@loadable/server/lib/ChunkExtractorManager.js:13:3)
Warning: Failed prop type: The prop `onSelectBlock` is marked as required in `Memo`, but its value is `undefined`.
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:105118:5
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:74014:5
    at StyleWrapper (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:34385:5)
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at div
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at RenderBlocks (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:95664:5)
    at div
    at $2e5fe81f2b094176$export$42a852a2b6b56249 (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:125707:17)
    at DefaultView (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:66301:5)
    at div
    at View (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:67570:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(View))
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at main
    at div
    at Segment (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/semantic-ui-react@2.1.5_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/semantic-ui-react/dist/commonjs/elements/Segment/Segment.js:28:24)
    at MultilingualRedirector (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:62687:5)
    at PluggablesProvider (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:50358:3)
    at App (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:59196:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(App))
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at AsyncConnect (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72173:5)
    at AsyncConnectWithContext (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72291:7)
    at C (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:731:37)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Router (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:99:30)
    at StaticRouter (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:587:35)
    at IntlProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl@3.12.1_react@18.2.0/node_modules/react-intl/dist/components/provider.js:89:47)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/Provider.js:19:3)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl-redux@2.3.0_@babel+runtime@7.20.6_prop-types@15.7.2_react-intl@3.12.1_react@18.2.0_tgk6nn4hyyhqsgqquyp6ne3siq/node_modules/react-intl-redux/lib/components/Provider.js:19:20)
    at CookiesProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-cookie@4.1.1_react@18.2.0/node_modules/react-cookie/cjs/CookiesProvider.js:52:24)
    at ChunkExtractorManager (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/@loadable+server@5.14.0_@loadable+component@5.14.1_react@18.2.0__react@18.2.0/node_modules/@loadable/server/lib/ChunkExtractorManager.js:13:3)
Warning: Failed prop type: The prop `pathname` is marked as required in `Memo`, but its value is `undefined`.
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:105118:5
    at /home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:74014:5
    at StyleWrapper (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:34385:5)
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at div
    at MaybeWrap (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:49073:7)
    at RenderBlocks (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:95664:5)
    at div
    at $2e5fe81f2b094176$export$42a852a2b6b56249 (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:125707:17)
    at DefaultView (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:66301:5)
    at div
    at View (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:67570:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(View))
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at main
    at div
    at Segment (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/semantic-ui-react@2.1.5_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/semantic-ui-react/dist/commonjs/elements/Segment/Segment.js:28:24)
    at MultilingualRedirector (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:62687:5)
    at PluggablesProvider (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:50358:3)
    at App (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:59196:5)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at injectIntl(Connect(App))
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at Switch (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:676:29)
    at Route (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:470:29)
    at AsyncConnect (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72173:5)
    at AsyncConnectWithContext (/home/plone/2024.ploneconf.org/frontend/core/packages/volto/build/server.js:72291:7)
    at C (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:731:37)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Router (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:99:30)
    at StaticRouter (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-router@5.2.0_react@18.2.0/node_modules/react-router/cjs/react-router.js:587:35)
    at IntlProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl@3.12.1_react@18.2.0/node_modules/react-intl/dist/components/provider.js:89:47)
    at ConnectFunction (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/connect.js:246:74)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-redux@8.1.2_@types+react-dom@18.2.12_@types+react@18.2.27_react-dom@18.2.0_react@18.2.0__react@18.2.0_redux@4.2.1/node_modules/react-redux/lib/components/Provider.js:19:3)
    at Provider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-intl-redux@2.3.0_@babel+runtime@7.20.6_prop-types@15.7.2_react-intl@3.12.1_react@18.2.0_tgk6nn4hyyhqsgqquyp6ne3siq/node_modules/react-intl-redux/lib/components/Provider.js:19:20)
    at CookiesProvider (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/react-cookie@4.1.1_react@18.2.0/node_modules/react-cookie/cjs/CookiesProvider.js:52:24)
    at ChunkExtractorManager (/home/plone/2024.ploneconf.org/frontend/node_modules/.pnpm/@loadable+server@5.14.0_@loadable+component@5.14.1_react@18.2.0__react@18.2.0/node_modules/@loadable/server/lib/ChunkExtractorManager.js:13:3)
```

**Comment by tkimnguyen** [comment]
With Firefox 129.0.2 it looks much better! 
![Screenshot 2024-09-11 at 9 42 50 AM](https://github.com/user-attachments/assets/a3d4f220-383d-41f8-bfd2-b01a99406b52)

**Comment by tkimnguyen** [comment]
Aw what the... I closed my Safari window and tried again in a new window and it works nicely: 
![Screenshot 2024-09-11 at 9 46 11 AM](https://github.com/user-attachments/assets/87beab04-4e68-4990-a311-1cc3495b02bd)

**Comment by tkimnguyen** [comment]
Initially in the Safari window that wasn't rendering the page correctly I didn't see *any* messages in the console.

**Comment by tkimnguyen** [comment]
Now, in the Safari window that renders the page properly (it would seem), this error appears 4 times in the console:

```
[Error] Warning: Failed prop type: The prop `index` is marked as required in `_c`, but its value is `undefined`.
_c@http://localhost:3001/static/js/client.js:204586:15
@http://localhost:3001/static/js/client.js:165495:29
StyleWrapper@http://localhost:3001/static/js/client.js:108632:12
MaybeWrap@http://localhost:3001/static/js/client.js:130814:189
div
MaybeWrap@http://localhost:3001/static/js/client.js:130814:189
RenderBlocks@http://localhost:3001/static/js/client.js:194004:12
div
Container@http://localhost:3001/static/js/client.js:333333:11
DefaultView@http://localhost:3001/static/js/client.js:154144:5
div
View@http://localhost:3001/static/js/client.js:155992:10
Connect(View)@http://localhost:3001/static/js/client.js:262054:110
injectIntl(Connect(View))
Route@http://localhost:3001/static/js/client.js:265195:34
Switch@http://localhost:3001/static/js/client.js:265401:34
main
div
Segment@http://localhost:3001/static/js/client.js:287806:23
MultilingualRedirector@http://localhost:3001/static/js/client.js:148877:13
PluggablesProvider@http://localhost:3001/static/js/client.js:132629:6
App@http://localhost:3001/static/js/client.js:143657:10
Connect(App)@http://localhost:3001/static/js/client.js:262054:110
injectIntl(Connect(App))
Connect(injectIntl(Connect(App)))@http://localhost:3001/static/js/client.js:262054:110
Route@http://localhost:3001/static/js/client.js:265195:34
Switch@http://localhost:3001/static/js/client.js:265401:34
Route@http://localhost:3001/static/js/client.js:265195:34
AsyncConnect@http://localhost:3001/static/js/client.js:162802:10
AsyncConnectWithContext@http://localhost:3001/static/js/client.js:162922:17
withRouter(AsyncConnectWithContext)@http://localhost:3001/static/js/client.js:265456:36
Connect(withRouter(AsyncConnectWithContext))@http://localhost:3001/static/js/client.js:262054:110
ScrollToTop@
Connect(ScrollToTop)@http://localhost:3001/static/js/client.js:262054:110
Router@http://localhost:3001/static/js/client.js:264824:34
ConnectedRouter@http://localhost:3001/static/js/client.js:12583:22
ConnectedRouterWithContext@http://localhost:3001/static/js/client.js:12689:24
Connect(ConnectedRouterWithContext)@http://localhost:3001/static/js/client.js:262054:110
IntlProvider@http://localhost:3001/static/js/client.js:259801:14
Connect(IntlProvider)@http://localhost:3001/static/js/client.js:262054:110
Provider@http://localhost:3001/static/js/client.js:261763:8
CookiesProvider@http://localhost:3001/static/js/client.js:212776:32
	printWarning (client.js:273332)
	error (client.js:273306)
	checkPropTypes (client.js:275197)
	validatePropTypes (client.js:275398)
	createElementWithValidation (client.js:275502)
	renderWithHooks (client.js:243759)
	mountIndeterminateComponent (client.js:247523)
	beginWork$1 (client.js:254875)
	performUnitOfWork (client.js:254006)
	workLoopSync (client.js:253915)
	renderRootSync (client.js:253883)
	performConcurrentWorkOnRoot (client.js:253187:89)
	workLoop (client.js:277428)
	flushWork (client.js:277401)
	performWorkUntilDeadline (client.js:277695)
```
